### ISSUE TITLE
[Bug] Please release 0.1.3

### ISSUE THREAD

**Issue by snowyegret23** [lilxyzw/lilEditorToolbox#1]
![1](https://github.com/user-attachments/assets/f1bdfb2c-6776-4942-95bc-d861ffa400c2)
The /vpm.json points to 0.1.3 as the latest version of lilEditorToolbox, 

![2](https://github.com/user-attachments/assets/838fe9a2-9725-4935-b9fc-9b8a06cae189)
but in actuality 0.1.3 has not been released.
Can you please release it?
Thanks.

**Comment by Misaka-L** [comment]
@lilxyzw

**Comment by lilxyzw** [comment]
I forgot the release
sry🙇
