### ISSUE TITLE
UnityPackageHighlighterのログが消しきれない

### ISSUE THREAD

**Issue by Sayamame-beans** [lilxyzw/lilEditorToolbox#10]
インポート→(ハイライトされている状態で)全てのログを削除→Unityを再起動すると、以下のような形でログが残っていました。
![image](https://github.com/user-attachments/assets/bc4bcfff-e5f8-45d6-8055-c4a1187064b2)

この後、もう一度削除を押して再起動すると、今度はログが表示されませんでした。
~~推測ですが、削除した時にハイライトした状態になっていた場合、そのログの実体が消えないのではないか?と思います。~~

Unity: 2022.3.22f1
lilEditorToolbox: v1.1.1

**Comment by Sayamame-beans** [comment]
> もう一度削除を押して再起動すると、今度はログが表示されませんでした。

この時に消えたログと同じパッケージをこの状態でインポートすると、前回インポートした分もハイライトされました…やはり消せていないようです?

**Comment by lilxyzw** [comment]
削除対象がハイライト中のunitypackageだった場合、ハイライトも削除するように修正してみました。

> この時に消えたログと同じパッケージをこの状態でインポートすると、前回インポートした分もハイライトされました…

ログに残る対象はインポートしたアセットではなくunitypackage内の全アセット（guid）なので仕様通りです。

**Comment by Sayamame-beans** [comment]
> > この時に消えたログと同じパッケージをこの状態でインポートすると、前回インポートした分もハイライトされました…
> 
> ログに残る対象はインポートしたアセットではなくunitypackage内の全アセット（guid）なので仕様通りです。

LogEditorからログを削除しているにもかかわらず、の後に(元々ログにあったパッケージをインポートすると、)ログが残っている時と同じ挙動をするのが気になっています

**Comment by Sayamame-beans** [comment]
すなわち、上記での流れは
1. 別のpackage→MilitCuteOnePiece(一部)という順でインポート/ログ構築が行われる
2. MilitCuteOnePieceのハイライトが残ったまま、LogEditorでこの2つのパッケージのログを削除する
3. Unityを再起動する
4. ハイライト対象として選択可能な内容はNoneのみになっている状態で、LogEditorにMilitCuteOnePieceが復活している
5. (ハイライトはNoneが選択された状態で)当該ログを削除する
6. Unityを再起動する
7. ハイライト対象がNoneで、LogEditorも空であることを確認する
8. MilitCuteOnePieceの一部(そのうちの1とは異なる部分)をインポートする
9. 1でインポートした部分と、9でインポートした部分の両方がハイライトされる(←消したはずのログが消えていない?)

となります
ややこしくてすみません…
