### ISSUE TITLE
UnityPackageHighlighterにおいて、異なるタイミングでインポートした同名のUnitypackageが同一のエントリとして扱われてしまう

### ISSUE THREAD

**Issue by Sayamame-beans** [lilxyzw/lilEditorToolbox#11]
同一のUnitypackageの一部だけをimportするような場合や、名前は同じだが内容が異なる場合などがあり得ると考えられるため、同一の名前であっても異なるエントリにした方が良いような気がしました。

Unity: 2022.3.22f1
lilEditorToolbox: v1.1.1

**Comment by lilxyzw** [comment]
インポートしたアセットだけでなく、unitypackage内の全アセットのguidがログに残るので前者のケースは問題ないと思います。
後者については既存のログの中に差分を追加する形で実装してみます。
