### ISSUE TITLE
UnityPackageHighlighterにおいて、インポートしたものの親フォルダも(何らかの形で)ハイライトして欲しい

### ISSUE THREAD

**Issue by Sayamame-beans** [lilxyzw/lilEditorToolbox#12]
例えば何らかの衣装をインポートした場合に、作者ごとのフォルダで内容が保存されていることがあるため、その中に増えた分だけがハイライトされても一見どこか分からないという問題が発生します。
![image](https://github.com/user-attachments/assets/9a454e94-bd05-40cc-8297-b65b7e0de8b8)

(インポートして更新された物そのものではないため、)全く同じ表示方法では紛らわしいという可能性はあります。
そのため、何らかの形(色を別にするとか、全体ではなく一部をハイライトするとか…?)で、インポートした内容の親フォルダにもハイライトをして欲しいと思います。

Unity: 2022.3.22f1
lilEditorToolbox: v1.1.1

**Comment by lilxyzw** [comment]
実装自体はできそうだけど全フォルダに対して子のオブジェクトを探索する処理が入るので重そうかも

**Comment by Sayamame-beans** [comment]
あ～…そういう感じなんですね…
なるほど…
