### ISSUE TITLE
hierarchy component disappeared

### ISSUE THREAD

**Issue by Itukii** [lilxyzw/lilEditorToolbox#2]
![image](https://github.com/user-attachments/assets/a9082c68-e03e-4b11-9a90-7edd1157105d)
Hello, I use lileditortoolbox,
It is very easy to display.
But when I updated to the latest 1.0, the hierarchy component on the right disappeared.
I don't know if it is a bug or needs new settings.
I want to know how to turn it on again.
Thank you.

I confirmed that it can be displayed normally in 0.1.8. But it disappeared in 0.1.8+...

**Comment by lilxyzw** [comment]
Open the preferences window and turn on the feature
https://lilxyzw.github.io/lilEditorToolbox/en_US/docs/Settings.html

**Comment by Itukii** [comment]
thanks! i works now
