### ISSUE TITLE
Scene上とScene Capture機能で保存される画像内で メガネ向けガラスシェーダー の見た目が異なる

### ISSUE THREAD

**Issue by shirasu256** [lilxyzw/lilEditorToolbox#8]
[メガネ向けガラスシェーダー Ver.2.2](https://booth.pm/ja/items/1035152) を使ったマテリアルを適用したオブジェクトをScene Captureすると、保存される画像内での見た目がScene上のそれと異なったものになっています。少し暗くなってしまう？

Scene上での見た目
![Scene上での見た目](https://github.com/user-attachments/assets/60965984-1232-4681-a708-3db733238e76)
実際に保存された画像
![実際に保存された画像](https://github.com/user-attachments/assets/0842bb8a-c96d-42c9-ba6e-ce2074056efd)

**Comment by lilxyzw** [comment]
該当シェーダーが出力する透明度が壊れているようでした。壊れているシェーダーに対しても正しく出力されるように修正を加えました。
