### ISSUE TITLE
Main Cameraオブジェクトが存在するSceneを複数同時にロードしている場合、Scene Capture機能を期待通りに使えない

### ISSUE THREAD

**Issue by shirasu256** [lilxyzw/lilEditorToolbox#9]
複数ロードしているSceneのうち、いずれか1つのScene上のものしか表示されません。
最初は機能名がScene View CaptureではなくScene Captureなので間違った挙動というわけでは無いかと思いましたが、[ドキュメント](https://lilxyzw.github.io/lilEditorToolbox/ja_JP/docs/EditorWindow/SceneCapture.html)に「Scene Viewで表示されている画面をそのままキャプチャし画像として保存」とあるので報告します。

**Comment by lilxyzw** [comment]
Scene_A・Scene_Bを作成し、それぞれにCubeを配置してキャプチャしてみましたが２つともキャプチャされ、問題は再現しませんでした。
こちら再現方法はありますか？
![image](https://github.com/user-attachments/assets/1d8fe9c1-8a83-46c9-95a3-a13a7cb39f41)

**Comment by shirasu256** [comment]
今こちらでももう一度試したのですが、「いずれか1つのScene上のものしか表示されない」は再現しませんでした…
別の問題があることはわかったので、自分がそれと混同して勘違いしたのかもしれません、すみません。
別途issueを立て直します。

**Comment by shirasu256** [comment]
https://github.com/lilxyzw/lilEditorToolbox/issues/13
